repos:
  # -----------------------------
  # Basic hygiene & safety checks
  # -----------------------------
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      # Prevent commiting large files (like .docx, .zip by mistake)
      - id: check-added-large-files
        args: ["--maxkb=500"]

      # Check python syntax validation
      - id: check-ast

      # Prevent commiting unresolved merge confliccts
      - id: check-merge-conflict

      # Ensure files end with a newline
      - id: end-of-file-fixer

      # Remove trailing whitespace
      - id: trailing-whitespace

      # Prevent commiting .env files
      - id: forbid-new-submodules
      - id: detect-private-key
